Style/Documentation: 
  Enabled: false

Metrics/AbcSize:
  Enabled: false

AllCops:
    SuggestExtensions: false
    
Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/FrozenStringLiteralComment:
 Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SafeNavigation:
 Enabled: false