default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: hotel_management_development
  username: developer
  password: 1234
  host: localhost

test:
  <<: *default
  database: hotel_management_test
  username: developer
  password: 1234
  host: localhost

production:
  <<: *default
  database: hotel_management_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
